### ISSUE TITLE
Google Web Fonts

### ISSUE THREAD

**Issue by epraxa** [theleagueof/licenses#1]
Is there any particular reason why your fonts aren't featured on Google's Web Fonts service? It allows you to choose your own open source license, even. Your fonts are beautiful, and my only lament is that I can't easily embed them on my websites with Google's Web Fonts.

If you're interested, the application to submit a font is located at https://services.google.com/fb/forms/submitafont/

Thank you so very much for your contributions to the design, typographic, and open source communities.

**Comment by ms-studio** [comment]
@epraxa : actually several of those fonts are available on Google:

Prociono: http://www.google.com/webfonts/specimen/Prociono
League Script: http://www.google.com/webfonts/specimen/League+Script
Sniglet: http://www.google.com/webfonts/specimen/Sniglet
etc. 

It's probably up to every designer to decide if they want to host their fonts in Google's repository.

**Comment by epraxa** [comment]
Ah, I see. I was having trouble finding any of the fonts on Google...Perhaps a Google Webfont link on each fonts' page (if available) would be nice to have?

Again, thanks for the site :D

**Comment by alerque** [comment]
Even more fonts than Manuel mentioned are already on Google Fonts. Raleway for example is there too.

I don't think there is any problem finding the font you are interested in on Google Fonts. If you see a font here and search for it there you will find it.

In the mean time there are actually significant disadvantages in hosting fonts there. Due to the limitations of their system (which has no versioning) it is kind of a one-shot deal. Once you publish there you can't update very well. Only updates that don't change rendering are ever allowed, otherwise you have to post under a new name. For open source fonts that are continuously improved this is a significant drawback. Also their platform doesn't support all OpenType features being used through their API.

Hence in most cases we'd *rather* people find the fonts and download them directly from us. For webfont usage there is also Fontsource which I'm [looking into closer integration with](https://github.com/fontsource/fontsource/issues/66) and also [direct publishing of NPM packages](https://github.com/alerque/libertinus/issues/366) that would automate setting up your own CDN (see e.g. [this discussion](https://github.com/alerque/libertinus/issues/362)).

More fonts will eventually make it into Google Fonts as well, but that's up to designers and needs to be done at a point where we're confident key metrics are not likely to EVER be changed. That should be tracked on a per-font basis and if you are interested in a specific font please post an issue on that font's issue tracker. I don't think there is anything actionable in total, and certainly not something that needs to be done to *this* repository.
